UPDATE menu_items SET image = '/images/menu/deccan-chai.jpg' WHERE name = 'Deccan Chai';
UPDATE menu_items SET image = '/images/menu/elaichi-tea.jpg' WHERE name = 'Elaichi Tea';
UPDATE menu_items SET image = '/images/menu/kadak-tea.jpg' WHERE name = 'Kadak Tea';
UPDATE menu_items SET image = '/images/menu/badam-tea.jpg' WHERE name = 'Badam Tea';
UPDATE menu_items SET image = '/images/menu/masala-tea.jpg' WHERE name = 'Masala Tea';
UPDATE menu_items SET image = '/images/menu/ginger-tea.jpg' WHERE name = 'Ginger Tea';
UPDATE menu_items SET image = '/images/menu/ginger-lemon-tea.jpg' WHERE name = 'Ginger Lemon Tea';
UPDATE menu_items SET image = '/images/menu/coffee.jpg' WHERE name = 'Coffee';
UPDATE menu_items SET image = '/images/menu/black-coffee.jpg' WHERE name = 'Black Coffee';
UPDATE menu_items SET image = '/images/menu/green-tea.jpg' WHERE name = 'Green Tea';
UPDATE menu_items SET image = '/images/menu/lemon-tea.jpg' WHERE name = 'Lemon Tea';
UPDATE menu_items SET image = '/images/menu/black-tea.jpg' WHERE name = 'Black Tea';
UPDATE menu_items SET image = '/images/menu/thati-bellam-tea.jpg' WHERE name = 'Thati Bellam Tea';
UPDATE menu_items SET image = '/images/menu/thati-bellam-coffee.jpg' WHERE name = 'Thati Bellam Coffee';
UPDATE menu_items SET image = '/images/menu/allam-bellam-coffee.jpg' WHERE name = 'Allam Bellam Coffee';
UPDATE menu_items SET image = '/images/menu/bellam-tea.jpg' WHERE name = 'Bellam Tea';
UPDATE menu_items SET image = '/images/menu/cold-coffee.jpg' WHERE name = 'Cold Coffee';
UPDATE menu_items SET image = '/images/menu/chilled-badam.jpg' WHERE name = 'Chilled Badam';
UPDATE menu_items SET image = '/images/menu/rose-milk.jpg' WHERE name = 'Rose Milk';
UPDATE menu_items SET image = '/images/menu/mango-lassi.jpg' WHERE name = 'Mango Lassi';
UPDATE menu_items SET image = '/images/menu/strawberry-lassi.jpg' WHERE name = 'Strawberry Lassi';
UPDATE menu_items SET image = '/images/menu/banana-lassi.jpg' WHERE name = 'Banana Lassi';
UPDATE menu_items SET image = '/images/menu/sweet-lassi.jpg' WHERE name = 'Sweet Lassi';
UPDATE menu_items SET image = '/images/menu/chocolate-lassi.jpg' WHERE name = 'Chocolate Lassi';
UPDATE menu_items SET image = '/images/menu/oreo.jpg' WHERE name = 'Oreo';
UPDATE menu_items SET image = '/images/menu/dark-chocolate.jpg' WHERE name = 'Dark Chocolate';
UPDATE menu_items SET image = '/images/menu/irish-cream.jpg' WHERE name = 'Irish Cream';
UPDATE menu_items SET image = '/images/menu/strawberry.jpg' WHERE name = 'Strawberry';
UPDATE menu_items SET image = '/images/menu/mango.jpg' WHERE name = 'Mango';
UPDATE menu_items SET image = '/images/menu/black-current.jpg' WHERE name = 'Black Current';
UPDATE menu_items SET image = '/images/menu/pineapple.jpg' WHERE name = 'Pineapple';
UPDATE menu_items SET image = '/images/menu/water-melon.jpg' WHERE name = 'Water Melon';
UPDATE menu_items SET image = '/images/menu/blue-mojito.jpg' WHERE name = 'Blue Mojito';
UPDATE menu_items SET image = '/images/menu/lime-mint.jpg' WHERE name = 'Lime Mint';
UPDATE menu_items SET image = '/images/menu/strawberry-mojito.jpg' WHERE name = 'Strawberry Mojito';
UPDATE menu_items SET image = '/images/menu/mango-mojito.jpg' WHERE name = 'Mango Mojito';
UPDATE menu_items SET image = '/images/menu/osmania-biscuit.jpg' WHERE name = 'Osmania Biscuit';
UPDATE menu_items SET image = '/images/menu/veg-puff.jpg' WHERE name = 'Veg Puff';
UPDATE menu_items SET image = '/images/menu/egg-puff.jpg' WHERE name = 'Egg Puff';
UPDATE menu_items SET image = '/images/menu/samosa.jpg' WHERE name = 'Samosa';
